name: Alpha67_plugin
version: '${version}'
main: com.vultorio.Alpha67.Alpha67
api-version: 1.16
authors: [ vultorio ]
commands:
  mod:
    description: display the mod by system
    usage: /<command>

